name: Publish GIT Wizard

on:
    push:
      tags:
        - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Release the version
        run: |
            docker build -t ghcr.io/sachintha00/api-staging:latest -f ./dockerfiles/production.Dockerfile .
            docker run -e NPMJS_AUTHENTICATION_KEY=${{ secrets.NPMJS_AUTHENTICATION_KEY }} -e RELEASE_VERSION=${{needs.set_version.outputs.RELEASE_VERSION}} ghcr.io/sachintha00/api-staging:latest
